package elemx

const (
	HREF            = "href"
	HTML_A_TAG      = "a"
	HTML_BODY_TAG   = "body"
	HTML_BUTTON_TAG = "button"
	HTML_DIV_TAG    = "div"
	HTML_FORM_TAG   = "form"
	HTML_H1_TAG     = "h1"
	HTML_H2_TAG     = "h2"
	HTML_H3_TAG     = "h3"
	HTML_H4_TAG     = "h4"
	HTML_H5_TAG     = "h5"
	HTML_H6_TAG     = "h6"
	HTML_HEAD_TAG   = "head"
	HTML_HTML_TAG   = "html"
	HTML_IMG_TAG    = "img"
	HTML_INPUT_TAG  = "input"
	HTML_LABEL_TAG  = "label"
	HTML_LI_TAG     = "li"
	HTML_LINK_TAG   = "link"
	HTML_OL_TAG     = "ol"
	HTML_P_TAG      = "p"
	HTML_SCRIPT_TAG = "script"
	HTML_SPAN_TAG   = "span"
	HTML_TABLE_TAG  = "table"
	HTML_TD_TAG     = "td"
	HTML_TITLE_TAG  = "title"
	HTML_TR_TAG     = "tr"
	HTML_UL_TAG     = "ul"
	HTMX_CDN_SOURCE = "https://unpkg.com/htmx.org@2.0.1"
	LANG            = "lang"
	NO_CONTENT      = ""
	REL             = "rel"
	SRC             = "src"
)

