package elemx

func Body(c string, attrs ...SetAttr) string   { return Render(HTML_BODY_TAG, c, attrs) }
func Div(c string, attrs ...SetAttr) string    { return Render(HTML_DIV_TAG, c, attrs) }
func Head(c string, attrs ...SetAttr) string   { return Render(HTML_HEAD_TAG, c, attrs) }
func Html(c string, attrs ...SetAttr) string   { return Render(HTML_HTML_TAG, c, attrs) }
func Link(attrs ...SetAttr) string             { return Render(HTML_LINK_TAG, NO_CONTENT, attrs) }
func P(c string, attrs ...SetAttr) string      { return Render(HTML_P_TAG, c, attrs) }
func Script(c string, attrs ...SetAttr) string { return Render(HTML_SCRIPT_TAG, c, attrs) }
func Title(c string, attrs ...SetAttr) string  { return Render(HTML_TITLE_TAG, c, attrs) }

// Generated by Copilot: check later
func A(c string, attrs ...SetAttr) string          { return Render(HTML_A_TAG, c, attrs) }          // Added by Copilot
func Button(c string, attrs ...SetAttr) string     { return Render(HTML_BUTTON_TAG, c, attrs) }     // Added by Copilot
func Form(c string, attrs ...SetAttr) string       { return Render(HTML_FORM_TAG, c, attrs) }       // Added by Copilot
func H1(c string, attrs ...SetAttr) string         { return Render(HTML_H1_TAG, c, attrs) }         // Added by Copilot
func H2(c string, attrs ...SetAttr) string         { return Render(HTML_H2_TAG, c, attrs) }         // Added by Copilot
func H3(c string, attrs ...SetAttr) string         { return Render(HTML_H3_TAG, c, attrs) }         // Added by Copilot
func H4(c string, attrs ...SetAttr) string         { return Render(HTML_H4_TAG, c, attrs) }         // Added by Copilot
func H5(c string, attrs ...SetAttr) string         { return Render(HTML_H5_TAG, c, attrs) }         // Added by Copilot
func H6(c string, attrs ...SetAttr) string         { return Render(HTML_H6_TAG, c, attrs) }         // Added by Copilot
func Img(attrs ...SetAttr) string                  { return Render(HTML_IMG_TAG, NO_CONTENT, attrs) } // Added by Copilot
func Input(attrs ...SetAttr) string                { return Render(HTML_INPUT_TAG, NO_CONTENT, attrs) } // Added by Copilot
func Label(c string, attrs ...SetAttr) string      { return Render(HTML_LABEL_TAG, c, attrs) }      // Added by Copilot
func Ol(c string, attrs ...SetAttr) string         { return Render(HTML_OL_TAG, c, attrs) }         // Added by Copilot
func Ul(c string, attrs ...SetAttr) string         { return Render(HTML_UL_TAG, c, attrs) }         // Added by Copilot
func Li(c string, attrs ...SetAttr) string         { return Render(HTML_LI_TAG, c, attrs) }         // Added by Copilot
func Span(c string, attrs ...SetAttr) string       { return Render(HTML_SPAN_TAG, c, attrs) }       // Added by Copilot
func Table(c string, attrs ...SetAttr) string      { return Render(HTML_TABLE_TAG, c, attrs) }      // Added by Copilot
func Tr(c string, attrs ...SetAttr) string         { return Render(HTML_TR_TAG, c, attrs) }         // Added by Copilot
func Td(c string, attrs ...SetAttr) string         { return Render(HTML_TD_TAG, c, attrs) }         // Added by Copilot