package elemx

const (
	HREF            string = "href"
	HTML_A_TAG      string = "a"
	HTML_BODY_TAG   string = "body"
	HTML_BUTTON_TAG string = "button"
	HTML_DIV_TAG    string = "div"
	HTML_FORM_TAG   string = "form"
	HTML_H1_TAG     string = "h1"
	HTML_H2_TAG     string = "h2"
	HTML_H3_TAG     string = "h3"
	HTML_H4_TAG     string = "h4"
	HTML_H5_TAG     string = "h5"
	HTML_H6_TAG     string = "h6"
	HTML_HEAD_TAG   string = "head"
	HTML_HTML_TAG   string = "html"
	HTML_IMG_TAG    string = "img"
	HTML_INPUT_TAG  string = "input"
	HTML_LABEL_TAG  string = "label"
	HTML_LI_TAG     string = "li"
	HTML_LINK_TAG   string = "link"
	HTML_OL_TAG     string = "ol"
	HTML_P_TAG      string = "p"
	HTML_SCRIPT_TAG string = "script"
	HTML_SPAN_TAG   string = "span"
	HTML_TABLE_TAG  string = "table"
	HTML_TD_TAG     string = "td"
	HTML_TITLE_TAG  string = "title"
	HTML_TR_TAG     string = "tr"
	HTML_UL_TAG     string = "ul"
	HTMX_CDN_SOURCE string = "https://unpkg.com/htmx.org@2.0.1"
	LANG            string = "lang"
	REL             string = "rel"
	SRC             string = "src"
)
